const NEXT_PUBLIC_API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const PRODUCTS_SERVICE_URL = `${NEXT_PUBLIC_API_BASE_URL}/products`;
const ORDERS_SERVICE_URL = `${NEXT_PUBLIC_API_BASE_URL}/orders`;

export { NEXT_PUBLIC_API_BASE_URL, PRODUCTS_SERVICE_URL, ORDERS_SERVICE_URL };
